[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#6C5CE7"
backgroundColor = "#0b0b0f"
secondaryBackgroundColor = "#1a1a1f"
textColor = "#f8f9fa"